framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - potential_spam
                - spam
                - rejected
                - ready
                - published
            transitions:
                accept:
                    from: submitted
                    to:   ham
                might_be_spam:
                    from: submitted
                    to:   potential_spam
                reject_spam:
                    from: submitted
                    to:   spam
                publish:
                    from: potential_spam
                    to:   ready
                reject:
                    from: potential_spam
                    to:   rejected
                publish_ham:
                    from: ham
                    to:   ready
                reject_ham:
                    from: ham
                    to:   rejected
                optimize:
                    from: ready
                    to: published
        admin_management:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Admin
            initial_marking: pending
            places:
                - pending      # do zatwierdzenia
                - active       # działający admin
                - suspended    # zawieszony admina
                - rejected     # odrzucenie aplikacji na admina
            transitions:
                activate:
                    from: pending
                    to: active
                    metadata:
                        title: 'Activate Admin'
                        description: 'Approve and activate the admin account'
                suspend:
                    from: active
                    to: suspended
                    metadata:
                        title: 'Suspend Admin'
                        description: 'Temporarily suspend the admin account'
                reactivate:
                    from: suspended
                    to: active
                    metadata:
                        title: 'Reactivate Admin'
                        description: 'Reactivate a suspended admin account'
                reject:
                    from: [pending, suspended]
                    to: rejected
                    metadata:
                        title: 'Reject Admin'
                        description: 'Permanently reject the admin application'
                restore:
                    from: rejected
                    to: pending
                    metadata:
                        title: 'Restore Admin'
                        description: 'Restore a rejected admin to pending status'