controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

"https://spa.{all}/": { type: upstream, upstream: "spa:http" }
"http://spa.{all}/": { type: redirect, to: "https://spa.{all}/" }
